name: SSH Deploy with Password

on:
  push:
    branches:
      - dev  # Se ejecuta solo en la rama dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Este paso revisa el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Instala expect para manejar el comando SSH con contraseña
      - name: Install Expect
        run: sudo apt-get install -y expect

      # Enviar comando SSH usando expect para manejar la contraseña
      - name: SSH into Server with Password
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          expect << EOF
          spawn ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST
          expect "password:"
          send "$SERVER_PASSWORD\r"
          expect "$ "
          send "./log.sh"
          expect "$ "
          send "exit\r"
          EOF
